CREATE USER PROJECTDB IDENTIFIED BY PROJECTDB;
GRANT CREATE SESSION TO PROJECTDB;
GRANT CREATE SESSION TO PROJECTDB WITH ADMIN  OPTION;
GRANT CREATE ANY TABLE TO PROJECTDB;
ALTER USER PROJECTDB QUOTA 50M ON SYSTEM;
GRANT CREATE SEQUENCE TO PROJECTDB;
GRANT CREATE TRIGGER TO PROJECTDB;
GRANT CREATE PROCEDURE TO PROJECTDB;